# Use a imagem base PHP 8.3 com FPM
FROM php:8.3-fpm

# Argumento para configurar a versão do Node.js
ARG NODE_VERSION=22

# Atualize os pacotes e instale dependências básicas
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    build-essential \
    unzip \
    git \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    net-tools \
    zip \
    nano \
    iputils-ping \
    netcat-openbsd \
    libssl-dev \
    pkg-config \
    supervisor \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd zip pdo_mysql ftp \
    && pecl install redis \
    && pecl install mongodb \
    && docker-php-ext-enable redis \
    && docker-php-ext-enable mongodb \
    && apt-get clean


# Copiar configurações do Supervisor para o path de execução
COPY .docker/supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Instale o Node.js versão 22
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm@latest \
    && npm install -g yarn \
    && npm cache clean --force

# Exibe as versões instaladas
RUN php -v && node -v && npm -v

# Instale o Composer globalmente
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /var/www/html

# Instalando dependencias do node.
RUN yarn install

# Copiando entrypoint
COPY .docker/dev/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Executando entrypoint
ENTRYPOINT ["/entrypoint.sh"]

# Expor a porta padrão do PHP-FPM
EXPOSE 9000

# Comando padrão ao iniciar o contêiner
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
