FROM php:8.3-cli

# Instala dependências
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libpq-dev \
    && docker-php-ext-install zip pdo pdo_mysql

# Instala Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


WORKDIR /var/www/html

# Instala as dependências do Laravel
RUN composer install --optimize-autoloader --no-dev

# Comando padrão (pode ser sobrescrito)
CMD ["php", "artisan", "queue:work"]
